### ISSUE TITLE
Add a check for TransparentHugePages enabled - Linux only

### ISSUE THREAD

**Issue by abonuccelli-es** [elasticsearch/elasticsearch-support-diagnostics#37]
THP enabled by default on most linux distros is known to cause long young GC

Add a check along the lines of 

https://access.redhat.com/solutions/46111

Ideally identify one single command working on both rpm/deb/any_other_major based distros

**Comment by jjfalling** [comment]
After discussing this we found it is better to not touch this and leave it set to what the os ships with.

**Comment by tristan0x** [comment]
Could you please share what lead you to this conclusion?

**Comment by jjfalling** [comment]
The lucene developers found that disabling THP without properly configuring hue pages in java and the OS cause performance issues in Lucene. See the test data points AV and AW here: http://people.apache.org/~mikemccand/lucenebench/PKLookup.html

**Comment by tristan0x** [comment]
Thank you :metal:
